### ISSUE TITLE
minimum stability - dev

### ISSUE THREAD

**Issue by frolof** [fedemotta/yii2-gridstack#1]
Hello,
Is it possible to change in composer.js line:
"bower-asset/gridstack":"> 0.2.2"
to:
"bower-asset/gridstack":">= 0.2.2"

Because this line require to lower minimum-stability of whole application to dev.

**Comment by fedemotta** [comment]
It is not possible because the 0.2.2 was not using bower yet. I am having the same issue and I am waiting for a 0.2.3 release (See [#136](https://github.com/troolee/gridstack.js/issues/136)).
You can use `"bower-asset/gridstack":"@dev"` in your composer file to avoid to lower your composer minimum stability.

**Comment by fedemotta** [comment]
You can use the 1.1 release tag to avoid the addition of the `"bower-asset/gridstack":"@dev"` to your composer file.
